# ⎧                                        ⎫
# ⎨  Startup                               ⎬
# ⎩                                        ⎭
after-login-command = []
after-startup-command = [
  'exec-and-forget borders active_color=0xff5E548E inactive_color=0xff555555 width=4.0',
  'exec-and-forget sketchybar'
]
start-at-login = true

# ⎧                                        ⎫
# ⎨  OnWorkspaceChange execs               ⎬
# ⎩                                        ⎭
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# ⎧                                        ⎫
# ⎨  Globals                               ⎬
# ⎩                                        ⎭
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
key-mapping.preset = 'qwerty'
default-root-container-orientation = 'auto'

# ⎧                                        ⎫
# ⎨  Padding                               ⎬
# ⎩                                        ⎭
[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       4
outer.bottom =     4
outer.top =        40
outer.right =      4

# ⎧                                        ⎫
# ⎨  Main Mode Keymaps                     ⎬
# ⎩                                        ⎭
[mode.main.binding]
# util
alt-shift-semicolon = 'mode service'
cmd-ctrl-r = ['reload-config', 'mode main']

# toggle between splits
cmd-slash = 'layout tiles horizontal vertical'

# focus a tile
cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

# move a tile
cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

# join tiles into a parent container
cmd-ctrl-h = ['join-with left', 'mode main']
cmd-ctrl-j = ['join-with down', 'mode main']
cmd-ctrl-k = ['join-with up', 'mode main']
cmd-ctrl-l = ['join-with right', 'mode main']

# window resizing
ctrl-minus = 'resize smart -50'
ctrl-equal = 'resize smart +50'
ctrl-enter = 'balance-sizes'
alt-f = 'fullscreen'

# switch to workspaces
cmd-1 = 'workspace 1'  # main: browser - work
cmd-2 = 'workspace 2'  # main: terminal
cmd-3 = 'workspace 3'  # main: code / IDE
cmd-4 = 'workspace 4'  # main: browser - fun
cmd-5 = 'workspace 5'  # main: workstations: vm's, word
cmd-6 = 'workspace 6'  # main: messaging
cmd-7 = 'workspace 7'  # main: OPEN
cmd-8 = 'workspace 8'  # secondary: steam
cmd-9 = 'workspace 9'  # secondary: util - vpn, docker
cmd-0 = 'workspace 10' # secondary spotify

# move app to workspace and switch
cmd-ctrl-1 = ['move-node-to-workspace 1',  'workspace 1']
cmd-ctrl-2 = ['move-node-to-workspace 2',  'workspace 2']
cmd-ctrl-3 = ['move-node-to-workspace 3',  'workspace 3']
cmd-ctrl-4 = ['move-node-to-workspace 4',  'workspace 4']
cmd-ctrl-5 = ['move-node-to-workspace 5',  'workspace 5']
cmd-ctrl-6 = ['move-node-to-workspace 6',  'workspace 6']
cmd-ctrl-7 = ['move-node-to-workspace 7',  'workspace 7']
cmd-ctrl-8 = ['move-node-to-workspace 8',  'workspace 8']
cmd-ctrl-9 = ['move-node-to-workspace 9',  'workspace 9']
cmd-ctrl-0 = ['move-node-to-workspace 10', 'workspace 10']

# open applications
ctrl-cmd-f = '''exec-and-forget open -na Firefox'''
ctrl-cmd-g = '''exec-and-forget open -na Ghostty'''
ctrl-cmd-d = '''exec-and-forget open -na Docker\ Desktop'''
ctrl-cmd-o = '''exec-and-forget open -na Obsidian'''
ctrl-cmd-s = '''exec-and-forget open -na Spotify'''

# ⎧                                        ⎫
# ⎨  Service Mode Keymaps                  ⎬
# ⎩                                        ⎭
[mode.service.binding]
esc = 'mode main'
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# ⎧                                        ⎫
# ⎨  App Specific Workspaces               ⎬
# ⎩                                        ⎭
# assign workspaces to monitors
[workspace-to-monitor-force-assignment]
1 =  'Odyssey G91SD|DELL*|main'
2 =  'Odyssey G91SD|DELL*|main'
3 =  'Odyssey G91SD|DELL*|main'
4 =  'Odyssey G91SD|DELL*|main'
5 =  'Odyssey G91SD|DELL*|main'
6 =  'Odyssey G91SD|DELL*|main'
7 =  'built-in*|secondary'
8 =  'built-in*|secondary'
9 =  'built-in*|secondary'
10 = 'built-in*|secondary'

# ⎧                                        ⎫
# ⎨  1. Firefox                            ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 1'

# ⎧                                        ⎫
# ⎨  2. Terminal Emulators                 ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'zathura'
run = 'move-node-to-workspace 2'

# ⎧                                        ⎫
# ⎨  3. Development (IDEs)                 ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = ['move-node-to-workspace 3']

# ⎧                                        ⎫
# ⎨  4. Notes                              ⎬
# ⎩                                        ⎭

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['move-node-to-workspace 4']

# ⎧                                        ⎫
# ⎨  5. Workstations                       ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.jetbrains.datagrip'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'org.wireshark.Wireshark'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = 'move-node-to-workspace 5'

# SQLDeveloper
[[on-window-detected]]
if.app-id = 'com.oracle.java.java'
run = 'move-node-to-workspace 5'

# ⎧                                        ⎫
# ⎨  6. Free                               ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = 'move-node-to-workspace 6'

# ⎧                                        ⎫
# ⎨  7. Messaging                          ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 7'

# ⎧                                        ⎫
# ⎨  8. Steam                              ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam.helper'
run = 'move-node-to-workspace 8'

# ⎧                                        ⎫
# ⎨  9. Util -- VPN, docker                ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.nordvpn.macos'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = 'move-node-to-workspace 9'

# ⎧                                        ⎫
# ⎨  10. Music                             ⎬
# ⎩                                        ⎭
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 10'

# ⎧                                        ⎫
# ⎨  Ignored Apps                          ⎬
# ⎩                                        ⎭
# Catch-all
[[on-window-detected]]
run = 'layout floating'
